# frozen_string_literal: true

# Wurk configuration. Generated by `bin/rails g wurk:install`.
# See docs/target/sidekiq-free.md for the full surface area.

Wurk.configure_server do |config|
  # config.redis = { url: ENV.fetch("REDIS_URL", "redis://localhost:6379/0") }
  # config.workers = 2
  # config.concurrency = 10
  # config.queues = %w[critical default low]
  # config.shutdown_timeout = 25
end

Wurk.configure_client do |config|
  # config.redis = { url: ENV.fetch("REDIS_URL", "redis://localhost:6379/0") }
end
