# frozen_string_literal: true

# Wurk configuration. Generated by `bin/rails g wurk:install`.
# Full surface area: docs/target/sidekiq-free.md. Coming from Sidekiq?
# See docs/migrate-from-sidekiq.md.

Wurk.configure_server do |config|
  # config.redis = { url: ENV.fetch("REDIS_URL", "redis://localhost:6379/0") }

  # Threads per worker process:
  # config.concurrency = 10

  # Queues this process pulls from (first = highest priority):
  # config.queues = %w[critical default low]

  # Seconds to let in-flight jobs finish on shutdown (Sidekiq-compatible key):
  # config[:timeout] = 25

  # The default is a single worker process (fork). To run several, declare a
  # topology — `flat` spawns N identical forks; use `slot`s for dedicated
  # queues. See docs/idea/03-process-model.md.
  # config.topology = Wurk::Topology.flat(count: 2, queues: %w[critical default low], concurrency: 10)
end

Wurk.configure_client do |config|
  # config.redis = { url: ENV.fetch("REDIS_URL", "redis://localhost:6379/0") }
end
