#!/usr/bin/env ruby
# frozen_string_literal: true

# Standalone runner. Does NOT load the Rails engine.
# Usage: `exe/wurk -C config/wurk.yml`

$stdout.sync = true
$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))

require 'wurk'

begin
  cli = Wurk::CLI.instance
  cli.parse
  cli.run
rescue StandardError => e
  raise e if $DEBUG

  warn "wurk: #{e.message}"
  warn e.backtrace.join("\n")
  exit 1
end
