# frozen_string_literal: true

require_relative '../engine_test_helper'

# Verifies that Rack::Static middleware is wired to serve precompiled SPA
# assets from vendor/assets/dashboard. Tests hashed filename serving and
# manifest validation.
class StaticAssetsTest < Wurk::Test::EngineCase
  ASSETS_DIR = ::Wurk::Engine.root.join('vendor', 'assets', 'dashboard')
  MANIFEST = ASSETS_DIR.join('wurk-manifest.json')

  def test_dashboard_manifest_is_generated_by_vite_build
    # The manifest is generated by the Vite build process in the
    # wurk-manifest-generator plugin. It contains the gem version
    # for boot-time validation in production.
    assert MANIFEST.exist?, "Manifest should be generated at #{MANIFEST}"
  end

  def test_dashboard_manifest_contains_version
    skip "Manifest file missing" unless MANIFEST.exist?

    data = JSON.parse(MANIFEST.read)
    assert_equal ::Wurk::VERSION, data['version']
  end

  def test_dashboard_manifest_contains_timestamp
    skip "Manifest file missing" unless MANIFEST.exist?

    data = JSON.parse(MANIFEST.read)
    assert data.key?('timestamp'), "Manifest should have a timestamp"
    # Verify it's ISO8601 formatted
    assert_match %r{\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}}, data['timestamp']
  end

  def test_rack_static_middleware_is_configured
    # The engine initializer configures Rack::Static to serve
    # files from vendor/assets/dashboard under the /wurk-assets prefix
    middleware = Rails.application.middleware

    static_middleware = middleware.find do |m|
      m.klass == ::Rack::Static
    end

    assert static_middleware, "Rack::Static middleware should be configured"
  end

  def test_vite_manifest_exists_for_asset_resolution
    # The .vite/manifest.json is used by the frontend to resolve
    # hashed filenames for linking in the SPA.
    vite_manifest = ASSETS_DIR.join('.vite', 'manifest.json')
    assert vite_manifest.exist?, ".vite/manifest.json should be generated by Vite"

    data = JSON.parse(vite_manifest.read)
    assert data.is_a?(Hash), "Vite manifest should be a JSON object"
    assert data.key?('index.html'), "Vite manifest should contain index.html entry"
  end

  def test_index_html_contains_hashed_filenames
    index = ASSETS_DIR.join('index.html')
    skip "index.html file missing" unless index.exist?

    content = index.read
    # Verify hashed filenames are present (Vite hash format: -XXXX.js/.css)
    assert_match %r{-[A-Za-z0-9_]+\.js}, content, "Should contain hashed JS filenames"
    assert_match %r{-[A-Za-z0-9_]+\.css}, content, "Should contain hashed CSS filenames"
  end

  def test_asset_files_exist_in_directory
    assets_subdir = ASSETS_DIR.join('assets')
    skip "assets subdirectory missing" unless assets_subdir.exist?

    files = Dir.glob("#{assets_subdir}/*.{js,css}")
    assert files.any?, "assets/ should contain built JS and CSS files"
  end
end
